import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copy } from "esbuild-plugin-copy";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

/**
 * esbuild plugin that patches onnxruntime-web for Obsidian compatibility.
 *
 * Obsidian plugins run in Electron's renderer with Node.js enabled, but:
 *   1. Dynamic import() of file:// or app:// URLs is blocked
 *   2. fetch() of file:// URLs is blocked
 *   3. import.meta.url is empty in CJS output
 *
 * This plugin fixes all three by patching at build time:
 *   - Inlines the Emscripten WASM glue (ort-wasm-simd-threaded.mjs) to avoid dynamic import
 *   - Forces the glue into Node.js mode so it uses fs.readFileSync instead of fetch
 *   - Removes the createRequire block that shadows CJS require
 *   - Replaces import.meta.url with a dummy URL for path resolution
 */
const ortObsidianPlugin = {
  name: "ort-obsidian",
  setup(build) {
    const ortDir = path.resolve("node_modules/onnxruntime-web/dist");
    const ortBundlePath = path.join(ortDir, "ort.wasm.bundle.min.mjs");
    const ns = "ort-obsidian";

    build.onResolve({ filter: /^onnxruntime-web$/ }, () => ({
      path: ortBundlePath,
      namespace: ns,
    }));

    build.onLoad({ filter: /.*/, namespace: ns }, async (args) => {
      let bundle = await fs.promises.readFile(args.path, "utf8");
      let glue = await fs.promises.readFile(path.join(ortDir, "ort-wasm-simd-threaded.mjs"), "utf8");

      // --- Patch the Emscripten glue (ort-wasm-simd-threaded.mjs) ---

      // Strip ESM export and trailing pthread worker auto-start code
      glue = glue.replace(/export\s+default\s+ortWasmThreaded[\s\S]*$/, "");

      // Include Electron renderer in Node.js detection (Emscripten excludes it by default).
      // This makes the glue use fs.readFileSync for WASM loading instead of fetch().
      glue = glue.replace(/&&\s*"renderer"\s*!=\s*globalThis\.process\?\.\s*type/, "");

      // Remove the createRequire + worker_threads block. It causes two problems:
      //   - import("module") fails in Obsidian's renderer
      //   - `var require = createRequire(...)` hoists and shadows esbuild's CJS require
      // CJS require is already available; workers aren't needed (numThreads=1).
      glue = glue.replace(
        /if\(m\)\{const \{createRequire:\w+\}=await import\("module"\);var require=\w+\(import\.meta\.url\)[^}]*\}/,
        "if(m){}"
      );

      // Replace import.meta.url (empty in CJS) with a valid dummy URL.
      // Only used for path resolution fallbacks — actual WASM path is set via ort.env.wasm.wasmPaths.
      glue = glue.replace(/import\.meta\.url/g, '"file:///plugin.js"');

      // --- Patch the ort bundle (ort.wasm.bundle.min.mjs) ---

      bundle = bundle.replace(/import\.meta\.url/g, '"file:///plugin.js"');

      // Replace the dynamic import() of the glue module with our inlined reference
      bundle = bundle.replace(
        /async\s+(\w)=>\(await import\([^)]*\1\)\)\.default/,
        "async $1=>__ortWasmGlue"
      );

      const contents = glue + "\nvar __ortWasmGlue = ortWasmThreaded;\n" + bundle;
      return { contents, loader: "js", resolveDir: ortDir };
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts", "src/styles.css"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir: "dist",
  plugins: [
    ortObsidianPlugin,
    copy({
      resolveFrom: "cwd",
      watch: !prod,
      assets: [
        { from: "manifest.json", to: "dist/manifest.json" },
        { from: "node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.wasm", to: "dist/ort-wasm-simd-threaded.wasm" },
      ],
    }),
  ],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
