import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copy } from "esbuild-plugin-copy";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const ortDir = path.resolve("node_modules/onnxruntime-web/dist")

/**
 * Patches onnxruntime-web glue + bundle for use inside a Web Worker.
 *
 * The worker receives the WASM binary via postMessage and sets ort.env.wasm.wasmBinary,
 * so no base64 inlining or Node.js fs mode is needed. The glue just needs:
 *   - ESM export stripped (bundled as IIFE)
 *   - Dynamic import() replaced with inlined reference
 *   - import.meta.url replaced (unavailable in IIFE)
 *   - createRequire block removed (no Node.js module system)
 */
async function buildWorkerOrtContents() {
  const ortBundlePath = path.join(ortDir, "ort.wasm.bundle.min.mjs");
  let bundle = await fs.promises.readFile(ortBundlePath, "utf8");
  let glue = await fs.promises.readFile(path.join(ortDir, "ort-wasm-simd-threaded.mjs"), "utf8");

  // Strip ESM export and trailing pthread worker auto-start code
  glue = glue.replace(/export\s+default\s+ortWasmThreaded[\s\S]*$/, "");

  // Remove the createRequire + worker_threads block
  glue = glue.replace(
    /if\(m\)\{const \{createRequire:\w+\}=await import\("module"\);var require=\w+\(import\.meta\.url\)[^}]*\}/,
    "if(m){}"
  );

  // Replace import.meta.url (unavailable in IIFE)
  glue = glue.replace(/import\.meta\.url/g, '"file:///plugin.js"');

  // Patch the ort bundle
  bundle = bundle.replace(/import\.meta\.url/g, '"file:///plugin.js"');

  // Replace dynamic import() of glue with inlined reference
  bundle = bundle.replace(
    /async\s+(\w)=>\(await import\([^)]*\1\)\)\.default/,
    "async $1=>__ortWasmGlue"
  );

  return glue + "\nvar __ortWasmGlue = ortWasmThreaded;\n" + bundle;
}

/**
 * esbuild plugin that patches onnxruntime-web for the Web Worker context.
 */
const ortWorkerPlugin = {
  name: "ort-worker",
  setup(build) {
    const ortBundlePath = path.join(ortDir, "ort.wasm.bundle.min.mjs");

    build.onResolve({ filter: /^onnxruntime-web$/ }, () => ({
      path: ortBundlePath,
      namespace: "ort-worker",
    }));

    build.onLoad({ filter: /.*/, namespace: "ort-worker" }, async () => ({
      contents: await buildWorkerOrtContents(),
      loader: "js",
      resolveDir: ortDir,
    }));
  },
};

/**
 * Shims Node.js builtins as empty objects for the worker build.
 * The Emscripten glue conditionally requires these in Node.js mode,
 * but a Web Worker takes the browser code path so they're never called.
 */
const nodeShimPlugin = {
  name: "node-shim",
  setup(build) {
    const shimmed = ["fs", "path", "url", "util", "os", "crypto", "worker_threads", "perf_hooks"];
    build.onResolve({ filter: new RegExp(`^(${shimmed.join("|")})$`) }, (args) => ({
      path: args.path,
      namespace: "node-shim",
    }));
    build.onLoad({ filter: /.*/, namespace: "node-shim" }, () => ({
      contents: "module.exports = {};",
      loader: "js",
    }));
  },
};

// Build the worker as a self-contained bundle

console.log("Building embedding worker...");
const workerBuild = await esbuild.build({
  entryPoints: ["src/embedding/embedding-worker.ts"],
  bundle: true,
  format: "iife",
  target: "es2020",
  write: false,
  minify: prod,
  plugins: [nodeShimPlugin, ortWorkerPlugin],
});
const workerCodeString = workerBuild.outputFiles[0].text;
console.log(`Worker bundle: ${(workerCodeString.length / 1024 / 1024).toFixed(1)} MB`);

// Plugins for the main bundle

/** Injects the worker code as a virtual ES module import */
const workerCodePlugin = {
  name: "worker-code",
  setup(build) {
    build.onResolve({ filter: /^virtual:embedding-worker$/ }, () => ({
      path: "virtual:embedding-worker",
      namespace: "worker-code",
    }));

    build.onLoad({ filter: /.*/, namespace: "worker-code" }, () => ({
      contents: `export default ${JSON.stringify(workerCodeString)};`,
      loader: "js",
    }));
  },
};

// Read WASM binary for injection into the main bundle banner.
// The main thread decodes this and transfers it to the worker via postMessage.
const wasmBuf = await fs.promises.readFile(path.join(ortDir, "ort-wasm-simd-threaded.wasm"));
const wasmB64 = wasmBuf.toString("base64");

// Build the main plugin bundle

const context = await esbuild.context({
  banner: { js: banner + `\nglobalThis.__ORT_WASM_BASE64 = "${wasmB64}";\n` },
  entryPoints: ["src/main.ts", "src/styles.css"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "onnxruntime-web",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir: "dist",
  plugins: [
    workerCodePlugin,
    copy({
      resolveFrom: "cwd",
      watch: !prod,
      assets: [
        { from: "manifest.json", to: "dist/manifest.json" },
      ],
    }),
  ],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
